default: &default
  adapter: postgresql
  encoding: unicode
  username: rainerborene
  pool: 5

development:
  <<: *default
  database: mailkiq_development

test:
  <<: *default
  database: mailkiq_test
  min_messages: notice

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
