development:
  paypal_sandbox: true
  paypal_username: rainerborene-facilitator_api1.gmail.com
  paypal_password: 2ENXAA4WGT6D5XD9
  paypal_signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AVzCo4aGnPmYOlxwwcapA2fSmEzp
  secret_key_base: 24a8ff0ac3affdfc02fcaf2c4facadd25a2dd8042e936c87bb83f8a8a4b16c901568d973c944ac43382371b97e4a52ca2c0afef49bf64d48b546ee188058f45e
  aws_access_key_id: AKIAIIQUXBCRN2WIK3UA
  aws_secret_access_key: 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

test:
  paypal_sandbox: true
  paypal_username: rainerborene-facilitator_api1.gmail.com
  paypal_password: 2ENXAA4WGT6D5XD9
  paypal_signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AVzCo4aGnPmYOlxwwcapA2fSmEzp
  secret_key_base: 1e5faf85a55080f8858aba74667c9654dc0601a09cdb0579cd30a85ecc0423a39be9f9bfb4946b15cb2307446bf16ed714f68b176d4d0fa009d7c4ef0a260476
  aws_access_key_id: AKIAIIQUXBCRN2WIK3UA
  aws_secret_access_key: 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

production:
  paypal_sandbox: <%= ENV['PAYPAL_SANDBOX'] %>
  paypal_username: <%= ENV['PAYPAL_USERNAME'] %>
  paypal_password: <%= ENV['PAYPAL_PASSWORD'] %>
  paypal_signature: <%= ENV['PAYPAL_SIGNATURE'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id: <%= ENV['MAILKIQ_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['MAILKIQ_SECRET_ACCESS_KEY'] %>
